/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/realistic_human_heart.glb --types 
Author: neshallads (https://sketchfab.com/neshallads)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/realistic-human-heart-3f8072336ce94d18b3d0d055a1ece089
Title: Realistic Human Heart
*/

import * as THREE from "three";

import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { ThreeElements } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    hartZBrush_defualt_group_Heart_Tex_0: THREE.Mesh;
  };
  materials: {
    Heart_Tex: THREE.MeshStandardMaterial;
  };
};

export function Model(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/realistic_human_heart.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.174}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.hartZBrush_defualt_group_Heart_Tex_0.geometry}
            material={materials.Heart_Tex}
            scale={286.365}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/realistic_human_heart.glb");
